# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locations_spoken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spoken_languages', to='theme_app.Location')),
            ],
        ),
    ]
