# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20170323_2326'),
        ('languages', '0002_auto_20170323_2331'),
    ]

    operations = [
    ]
