# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_app', '0001_initial'),
        ('languages', '0003_merge_20170323_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='locations_spoken',
        ),
        migrations.AddField(
            model_name='language',
            name='locations_spoken',
            field=models.ManyToManyField(null=True, related_name='spoken_languages', to='theme_app.Location'),
        ),
    ]
