# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='zip_code',
        ),
    ]
